name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'
      - name: Extract zip
        run: unzip JL-Mod-0.87.1.zip
      - name: Create keystore
        run: |
          cd JL-Mod-0.87.1
          keytool -genkey -v -keystore debug.keystore -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Android Debug,O=Android,C=US"
          echo "keyAlias=androiddebugkey" > keystore.properties
          echo "keyPassword=android" >> keystore.properties
          echo "storeFile=debug.keystore" >> keystore.properties
          echo "storePassword=android" >> keystore.properties
      - name: Build
        run: cd JL-Mod-0.87.1 && chmod +x gradlew && ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: apk-nokia
          path: JL-Mod-0.87.1/app/build/outputs/apk/debug/app-debug.apk
